### ISSUE TITLE
바이너리 서치 문서 예시 타이틀 추가 요청

### ISSUE THREAD

**Issue by hidekuma** [HiDIKI/hidiki.github.io.build#32]
- 별건아니고 해당 문서 예시 타이틀을 기존 문서와 일치시켜주셨으면 합니다! (###)
- 예시 1번 같은경우 좀더 내용을 알기 쉽게 보여주면 좋을 것같아요 ㅠ

**Comment by wabi91** [comment]
- 해당 문서 예시 타이틀을 기존 문서와 일치완료.
- 예시 1번 더 상세히 이쁘게 친절하게 설명하는 글로 수정.
