### ISSUE TITLE
asynchronous-programming-3  오탈자 수정

### ISSUE THREAD

**Issue by juunone** [HiDIKI/hidiki.github.io.build#47]
기초 예시1) 3번째줄
AS-IS = yield 'Teak';
TO-BE = yield 'Taek'; 

예시 1-1) 1번째줄 
AS-IS = const users = ['Wabi','Teak','Tesilio','Hidekuma','One'];
TO-BE = const users = ['Wabi','Taek','Tesilio','Hidekuma','One'];

예시 1-2) 28번째줄
AS-IS = name : "Teak"
TO-BE = name : "Taek" 

코루틴 노티 아래 예시) 20번째줄
AS-IS = // Teak (랜덤한 이름)
TO-BE = // Taek (랜덤한 이름)

@DeveloperYB 이정도면 택 안티아님?

**Comment by hidekuma** [comment]
ㅋㅋㅋ 틱장애 만드네

**Comment by wabi91** [comment]
@hidekuma  Close HiDIKI#47, merge 안하시고 close 하셨습니다.

**Comment by hidekuma** [comment]
@DeveloperYB 
푸시하셨나요 변경점이 없어서 비교할 내용이 없는데요 PR보내세요~

**Comment by hidekuma** [comment]
재오픈합니다

**Comment by wabi91** [comment]
다시 변경점 생성해서 올렸습니다.

**Comment by hidekuma** [comment]
@DeveloperYB PR안왔어요 와비님

**Comment by wabi91** [comment]
@hidekuma 다시 확인 부탁드립니다 :)
