### ISSUE TITLE
why-choose-react.md 수정요청

### ISSUE THREAD

**Issue by hidekuma** [HiDIKI/hidiki.github.io.build#6]
### 문서내 > 리액트 단점 부분
- 장점처럼 보다 구체적인 단점을 예로 들면 좋을것 같아요.
- 좀더객관적인 시점으로 비교분석해주시길 바래요. 
- 추후에 요즘 뜨는 Vue.js와 React.js를 비교분석하는 포스팅이 너무 재밌을것 같아요. @taekbari

**Comment by wabi91** [comment]
문서내 > 리액트 단점 부분

장점부분처럼 단점 부분 글 보완 및 정리
