### ISSUE TITLE
Plz check promise-resolve-order.md

### ISSUE THREAD

**Issue by hidekuma** [HiDIKI/hidiki.github.io.build#67]
issued by @DeveloperYB 
- reduce 부분에 array가 새로운 반환 array가 아님

Solution:
```javascript
const delay = ms => new Promise(resolve => setTimeout(resolve(ms), ms));
const msList = [500, 200, 3000, 200, 100];

const result = msList.reduce(async (acc, val) => {
    const reArr = await acc;
    const res = await delay(val);
    reArr.push(res);
    return reArr;
}, Promise.resolve([])).then(res => console.log(res));
```

is right?

**Comment by wabi91** [comment]
멋져요 맞습니다.
한번씩들 재확인이 필요합니다.
저는 아래 처럼 썼습니다.
해서, 반환값도 잘 받는것 확인했습니다. (아래 reduce는 lodash reduce 입니다.)
```js
const resultExtraImgArr = reduce(extraImgArr, async (acc, file, idx) => {
    const reAcc = await acc;
    const extraImageData = new FormData();
    extraImageData.append('image[image_file]', file);
    extraImageData.append('image[is_cover]', false);
    const res = await createImage({
        imageName: file.name,
        data: {
        product_id,
        data: extraImageData,
        },
    });
    reAcc.push(res);
    return reAcc;
}, Promise.resolve([]));
extraImagesRes = await resultExtraImgArr;
```

**Comment by hidekuma** [comment]
@tesilio @DeveloperYB 
이거 언제해주꼬야

**Comment by tesilio** [comment]
@hidekuma @DeveloperYB 
무슨말인지 이해가 안가서 설명이 필요합니다잉

**Comment by tesilio** [comment]
@hidekuma @DeveloperYB 
이해 했습니다. 반환해주는 Array가 새로운 Array가 아니라 기존의 Array라는 뜻이군요!
하지만 저 원본 코드의 목적은 비동기 호출을 동기적으로 순서 보장을 해주는 것이기 때문에 새로운 Array로 반환을 하든, 기존 Array를 바꾸든 상관이 없습니다. 그러나 새로운 Array로 반환을 해주는게 뭔가 더 좋을 것 같네요!

근시일 내에 수정해서 PR 하겠습니다!

**Comment by wabi91** [comment]
아 메일 확인하고 이제서야 봤습니다
네네 로직상 큰 문제는 없지만.
Promise.all 에 위 로직을 쓸경우에는 새 배열로 반환이 맞기 때문에
위 비동기 완료순서 보장 로직 (?) 에는 새 배열 반환이 좋다고 생각합니다.

아 그리고 저거 테스트 할때 setTimeout 으로 비동기 상태 만들어서 해봤는데요
잘 안되더라구요. ㅋㅋㅋ API 연동해서 테스트는 잘만 되던데...
뭔가 setTimeout 스텍에 쌓이는 경우에는 콘솔로 로그 찍는게 잘 안되나봐요.
(크롬 콘솔창에서 해본거라서 안될수도)
node 로 테스트하면 잘될 수도 있습니다 ㅋㅋㅋㅋㅋ
수정하시면 바로 볼게요!!
