### ISSUE TITLE
Change <Author/> 

### ISSUE THREAD

**Issue by hidekuma** [HiDIKI/hidiki.github.io.build#76]
- AS-IS
```
---
customauthor:
  - name: Bluemoon
---
```
더이상 상기 포맷은 사용안함.
- TO-BE
```<Author name="Bluemoon" />```

컨트리뷰팅에 반영을 안해놨던가..?
해놨네..? 성주띠^^
https://github.com/HiDIKI/hidiki.github.io.build/blob/master/CONTRIBUTING.md#-%EB%B6%80%EA%B0%80%EA%B8%B0%EB%8A%A5
수정해주세영

**Comment by liquidjoo** [comment]
알겠습니다~ :>
